import os

# DATABASE CONFIG
DATABASE_URL = os.getenv('DATABASE_URL')

DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')
DATABASE_HOST = os.getenv('DATABASE_HOST', 'jmoney_db')
DATABASE_PORT = os.getenv('DATABASE_PORT', '3306')
DATABASE_NAME = os.getenv('DATABASE_NAME', 'jmoney')

if DATABASE_URL:
    SQLALCHEMY_DATABASE_URI = DATABASE_URL
else:
    if not DATABASE_USER or not DATABASE_PASSWORD:
        raise RuntimeError('DATABASE_USER and DATABASE_PASSWORD must be set (or provide DATABASE_URL).')
    SQLALCHEMY_DATABASE_URI = f"mysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False
