"""Additional fields to User

Revision ID: 8c19b05ce5c9
Revises: f08a1373773e
Create Date: 2025-02-25 19:19:31.256982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c19b05ce5c9'
down_revision = 'f08a1373773e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
