"""Add end_date field to expense_type

Revision ID: 940f1d243748
Revises: 8c19b05ce5c9
Create Date: 2025-07-02 14:42:55.011298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940f1d243748'
down_revision = '8c19b05ce5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_type', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
